### ISSUE TITLE
None.get

### ISSUE THREAD

**Issue by biaoma-ty** [f7753/spark-1.4.1-prefetch#2]
org.apache.spark.shuffle.FetchFailedException: java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:313)
    at scala.None$.get(Option.scala:311)
    at org.apache.spark.network.netty.BlockCache$.get(BlockCache.scala:27)

**Comment by biaoma-ty** [comment]
This bug is introduced by the hashMap, if one prepare request put the K,V in the hashMap, then the open request is asked the hashMap to get the KV, the two request may in different thread, so the un-consistency occured.
Use JDK's concurrentHashMap fixed this bug.
